### ISSUE TITLE
[TYPO] Erro de digitação

### ISSUE THREAD

**Issue by kakamorsch** [Niel100/Exerc-cio-10.-Imagens-din-micas-m-dias-e-videos#1]
Ao invés de estar `pt-br` está `pt-be`.

https://github.com/Niel100/Exerc-cio-10.-Imagens-din-micas-m-dias-e-videos/blob/312e321e99241e4fcc0d15ad66533c0aea6d0875/index.html#L2

**Comment by Niel100** [comment]
obrigado @kakamorsch
